In [4]:
%mv /Users/kimjihun/Downloads/한국도로공사_교통사고통계_20211231.csv .

mv: /Users/kimjihun/Downloads/한국도로공사_교통사고통계_20211231.csv: No such file or directory

In [11]:
%pwd

'/Users/kimjihun/Documents/2022/DataScience/file-path'

In [5]:
%ls

file-path-setting.ipynb
한국도로공사_교통사고통계_20211231.csv

In [7]:
import pandas as pd

In [10]:
# ()안에서 shift + tab 키를 누르시면 도움말을 보실 수 있습니다.
pd.read_csv("data/한국도로공사_교통사고통계_20211231.csv", encoding="cp949")

      연도    사고   사망    부상
0   2000  3910  569  2845
1   2001  3638  456  2331
2   2002  3957  421  2115
3   2003  3585  348  1843
4   2004  3242  300  1555
5   2005  2880  249  1170
6   2006  2583  284  1131
7   2007  2550  283  1114
8   2008  2449  265   955
9   2009  2374  248  1031
10  2010  2368  353   983
11  2011  2640  265  1731
12  2012  2600  343  1619
13  2013  2496  264  1253
14  2014  2395  253  1148
15  2015  2251  223  1054
16  2016  2195  239  1424
17  2017  2145  214   911
18  2018  2030  227   858
19  2019  1931  176   830
20  2020  1834  179   861
21  2021  1735  171   794